[project]
name = "qwen3-tts-studio-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "qwen-tts>=0.0.5",
    "soundfile>=0.13.1",
]
